import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import Title from "antd/es/typography/Title";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const menuItems = [
    { key: "Home", label: "Home" },
    { key: "Projects", label: "Projects" },
  ];
  return (
    <html lang="en">
      <div className="navbar-container">
        <div className="custom-navbar">
          {menuItems.map((item: any) => (
            <Title key={item} level={5} style={{ color: "white", margin: 0 }}>
              {item.label}
            </Title>
          ))}
        </div>
      </div>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
